name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 790862075478.dkr.ecr.us-east-1.amazonaws.com/image-caching.net:latest
        cache-from: type=registry,ref=790862075478.dkr.ecr.us-east-1.amazonaws.com/image-caching.net:cache
        cache-to: type=registry,ref=790862075478.dkr.ecr.us-east-1.amazonaws.com/image-caching.net:cache,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
